include:
  - project: 'article714/build-tools'
    ref: master
    file: 'ci/docker-job-templates.yml'

stages:
  - build
  - quality
  - test
  - security
  - publish

variables:
  CI_DEBUG_TRACE: 'true'
  IMAGE_NAME: ansible714-docker
  IMAGE_VERSION: testing
  # following might be overriden by ansible714 project configuration
  PYTHON_VERSION: '3.9.2'
  DEBIAN_VERSION: 'buster'

#***********************************************************************
#
# Images are only built and published when pipeline is triggered from ansible714 project
#

#-----------------------------------------
# build_image:
#   extends: .build_image
#   variables:
#     DOCKER_ADDTL_PARAMS: '--build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg DEBIAN_VERSION=${DEBIAN_VERSION}'
#
# #------------------------------------------
# # Tests
#
# test_config:
#   extends: .test_image
#   script:
#     - python --version
#     - ansible --version
#     - cd /home/ansible
#     - ansible-config view
#
# test_ping:
#   extends: .test_image
#   script:
#     - cd /home/ansible
#     - ansible -m ping localhost
#
# test_check_update:
#   extends: .test_image
#   script:
#     - cd /home/ansible
#     - ansible-playbook --check playbooks/update-software.yml
#
# test_dns:
#   extends: .test_image
#   script:
#     - cd /home/ansible
#     - ansible-playbook -i ansible714/tests/target.yml ansible714/tests/test_dns_loop.yml
#
#------------------------------------------
# Publish images

publish_release:
  extends: .publish_image
  variables:
    IMAGE_TAG: ${PIPELINE_COMMIT_TAG}
  rules:
    - if: $CI_PIPELINE_SOURCE == 'pipeline' && $PIPELINE_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == 'pipeline' && $CI_COMMIT_TAG

publish_latest:
  extends: .publish_image
  variables:
    IMAGE_TAG: 'latest'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'pipeline' && $CI_COMMIT_BRANCH == 'master'
