stages:
  - build
  - tests
  - publish_images

variables:
  ANSIBLE714_DOCKER_VERSION: "0.0.1"
  ANSIBLE_VERSION: "2.9.9"

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - docker build ${BUILD_OPTS} -t article714/ansible714-docker:${ANSIBLE714_DOCKER_VERSION} --build-arg ANSIBLE714_DOCKER_VERSION=${ANSIBLE714_DOCKER_VERSION} --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION} .

#------------------------------------------
# Tests

test_image:
  stage: tests
  image:
    name: article714/ansible714-docker:${ANSIBLE714_DOCKER_VERSION}
  tags:
    - docker
  script:
    - ansible --version
    - cd /home/ansible
    - ansible-config view
    - ansible -m ping localhost
    - ansible-playbook --check /home/ansible/playbooks/update-software.yml

publish_image:
  stage: publish_images
  tags:
    - shell
  only:
    refs:
      - production
  script:
    - docker push article714/ansible714-docker:${ANSIBLE714_DOCKER_VERSION}
    - docker push article714/ansible714-docker:latest
