language: python
sudo: false
cache: pip

python:
  # For branches <= 10.0, put `- "2.7.13"`
  - "3.5"

services:
  - docker

script:
  - export BUILD_OPTS='--force-rm --no-cache'
  - export ANSIBLE714_DOCKER_VERSION='0.0.1'
  - export ANSIBLE_VERSION='2.9.9'
  - docker build ${BUILD_OPTS} -t article714/ansible714:${ANSIBLE714_DOCKER_VERSION} --build-arg ANSIBLE714_DOCKER_VERSION=${ANSIBLE714_DOCKER_VERSION} --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION} .
